workflows:
  react-native-ios:
    name: iOS Build and Upload - AlBashayera
    max_build_duration: 60
    environment:
      node: 18
      cocoapods: default
      xcode: latest
      vars:
        XCODE_PROJECT: "ios/AlBashayera.xcodeproj"
        XCODE_SCHEME: "AlBashayera"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.albashayera.albashayera"
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install || true
          cd ..
      - name: Build iOS App
        script: |
          xcodebuild -project $XCODE_PROJECT -scheme $XCODE_SCHEME -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/AlBashayera.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/AlBashayera.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $CM_BUILD_DIR/exported
    artifacts:
      - $CM_BUILD_DIR/exported/*.ipa
