workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment: {}
    scripts:
      - name: Install Dependencies
        script: |
          npm install
          cd ios
          pod install
      - name: Build iOS App
        script: |
          xcodebuild -workspace ios/AlBashayera.xcworkspace \
                     -scheme AlBashayera \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/AlBashayera.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/AlBashayera.xcarchive \
                     -exportOptionsPlist ios/exportOptions.plist \
                     -exportPath build/output
    artifacts:
      - build/output/*.ipa
